

services:
  nats:
    image: nats
    ports:
      - "4222:4222"
  redis:
    image: redis
    ports:
      - "6379:6379"

  order-service:
    build: 
        context: ./m_orders
        args:
        - MY_ENV_VAR
    ports:
      - "8083:8083"
    depends_on:
      - nats
    env_file:
      - ./m_orders/.env  
    volumes:
      - ./m_orders/.env:/.env 
      
  product-service:
    build: 
        context: ./m_products
        args:
        - MY_ENV_VAR
    ports:
      - "8082:8082"
    env_file:
      - ./m_products/.env
    volumes:
      - ./m_products/.env:/.env 

  user-service:
    build: 
        context: ./m_auth
        args:
        - MY_ENV_VAR
    ports:
      - "8080:8080"
    env_file:
      - ./m_auth/.env
    volumes:
      - ./m_auth/.env:/.env 

  producer-service:
    build: ./m_producer
    ports:
      - "50054:50054"
    depends_on:
      - nats

  consumer-service:
    build: ./m_consumer
    depends_on:
      - nats
      - product-service

  api-gateway:
    build: ./api
    ports:
      - "8081:8081"
    depends_on:
      - user-service
      - order-service
      - product-service

